// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCL81M_edUzAedzXTUoUL7bHyM2HHc_aQ',
    appId: '1:510945752221:web:7bf93141797922179d1074',
    messagingSenderId: '510945752221',
    projectId: 'boticart-93a0a',
    authDomain: 'boticart-93a0a.firebaseapp.com',
    storageBucket: 'boticart-93a0a.firebasestorage.app',
    measurementId: 'G-Q2JEEJBQRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuK0Wlr85Vg6ZKHnH0cfibR6DPssB57Yg',
    appId: '1:510945752221:android:ac9c82658f4db7c59d1074',
    messagingSenderId: '510945752221',
    projectId: 'boticart-93a0a',
    storageBucket: 'boticart-93a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLg-rk4tt8l2YdCdcidYEdsx7LBhZrzLs',
    appId: '1:510945752221:ios:bf9fd2999f4fa3f29d1074',
    messagingSenderId: '510945752221',
    projectId: 'boticart-93a0a',
    storageBucket: 'boticart-93a0a.firebasestorage.app',
    iosClientId:
        '510945752221-iu2mla4o27q1eihnl3sjqcabp33k0rti.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.app.boticart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLg-rk4tt8l2YdCdcidYEdsx7LBhZrzLs',
    appId: '1:510945752221:ios:bf9fd2999f4fa3f29d1074',
    messagingSenderId: '510945752221',
    projectId: 'boticart-93a0a',
    storageBucket: 'boticart-93a0a.firebasestorage.app',
    iosClientId:
        '510945752221-iu2mla4o27q1eihnl3sjqcabp33k0rti.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.app.boticart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqfgf4SZpOL2dxtf7Rg53AssmrtjxFHdQ',
    appId: '1:510945752221:web:2a70ce331f7368ba9d1074',
    messagingSenderId: '510945752221',
    projectId: 'boticart-93a0a',
    authDomain: 'boticart-93a0a.firebaseapp.com',
    storageBucket: 'boticart-93a0a.firebasestorage.app',
    measurementId: 'G-N38RYCPYE3',
  );
}
